"""
Output Formatter Module

This module handles formatting and modulation of AI-generated outputs,
including watermarking, sanitization, and content transformation.
"""

import logging
import json
import hashlib
from typing import Dict, Optional, Any, List
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class OutputFormat(Enum):
    """Supported output formats"""
    TEXT = "text"
    JSON = "json"
    MARKDOWN = "markdown"
    HTML = "html"
    XML = "xml"


class ContentPolicy(Enum):
    """Content filtering policies"""
    STRICT = "strict"
    MODERATE = "moderate"
    PERMISSIVE = "permissive"


class OutputFormatter:
    """
    Formats and modulates AI-generated content with watermarking and compliance.
    """

    def __init__(self, config: Optional[Dict] = None):
        """
        Initialize the Output Formatter.

        Args:
            config: Optional configuration dictionary
        """
        self.config = config or {}
        self.watermark_enabled = self.config.get("watermark_enabled", True)
        self.content_policy = ContentPolicy(self.config.get("content_policy", "moderate"))
        logger.info(f"OutputFormatter initialized with policy: {self.content_policy.value}")

    def format_output(
        self,
        content: Any,
        output_format: OutputFormat = OutputFormat.TEXT,
        metadata: Optional[Dict] = None
    ) -> Dict[str, Any]:
        """
        Format AI-generated content with watermarking and metadata.

        Args:
            content: The content to format
            output_format: Desired output format
            metadata: Optional metadata to include

        Returns:
            Formatted output with metadata
        """
        logger.debug(f"Formatting output as {output_format.value}")

        # Apply content filtering
        filtered_content = self._filter_content(content)

        # Apply watermark if enabled
        if self.watermark_enabled:
            watermarked_content = self._apply_watermark(filtered_content, metadata)
        else:
            watermarked_content = filtered_content

        # Format based on type
        formatted = self._apply_format(watermarked_content, output_format)

        # Prepare response
        result = {
            "content": formatted,
            "format": output_format.value,
            "metadata": self._generate_metadata(metadata),
            "watermarked": self.watermark_enabled,
            "timestamp": datetime.now().isoformat()
        }

        return result

    def _filter_content(self, content: Any) -> Any:
        """
        Apply content filtering based on policy.

        Args:
            content: Content to filter

        Returns:
            Filtered content
        """
        if not isinstance(content, str):
            return content

        # Apply policy-based filtering
        if self.content_policy == ContentPolicy.STRICT:
            # Strict filtering - remove potentially sensitive content
            filtered = self._apply_strict_filtering(content)
        elif self.content_policy == ContentPolicy.MODERATE:
            # Moderate filtering - basic sanitization
            filtered = self._apply_moderate_filtering(content)
        else:
            # Permissive - minimal filtering
            filtered = content

        return filtered

    def _apply_strict_filtering(self, content: str) -> str:
        """Apply strict content filtering."""
        # Placeholder for strict filtering logic
        # In production, this would check against prohibited content lists
        return content

    def _apply_moderate_filtering(self, content: str) -> str:
        """Apply moderate content filtering."""
        # Basic sanitization
        # Remove any potential script injections
        filtered = content.replace("<script>", "").replace("</script>", "")
        return filtered

    def _apply_watermark(self, content: Any, metadata: Optional[Dict]) -> Any:
        """
        Apply digital watermark to content.

        Args:
            content: Content to watermark
            metadata: Metadata for watermark generation

        Returns:
            Watermarked content
        """
        if not isinstance(content, str):
            return content

        watermark_data = {
            "generator": "AshborneSDK",
            "timestamp": datetime.now().isoformat(),
            "metadata": metadata or {}
        }

        # Generate watermark signature
        signature = self._generate_signature(watermark_data)

        # Append watermark (visible or invisible based on config)
        if self.config.get("visible_watermark", False):
            watermarked = f"{content}\n\n<!-- Generated by AshborneSDK - {signature} -->"
        else:
            # Invisible watermark embedded in content
            watermarked = content
            # Store signature in metadata for verification

        logger.debug(f"Applied watermark with signature: {signature[:16]}...")
        return watermarked

    def _apply_format(self, content: Any, output_format: OutputFormat) -> str:
        """
        Apply specific output format to content.

        Args:
            content: Content to format
            output_format: Target format

        Returns:
            Formatted content string
        """
        if output_format == OutputFormat.JSON:
            if isinstance(content, str):
                return json.dumps({"text": content}, indent=2)
            return json.dumps(content, indent=2)

        elif output_format == OutputFormat.MARKDOWN:
            if isinstance(content, str):
                return content
            return f"```json\n{json.dumps(content, indent=2)}\n```"

        elif output_format == OutputFormat.HTML:
            if isinstance(content, str):
                return f"<div class='ai-content'>{content}</div>"
            return f"<pre>{json.dumps(content, indent=2)}</pre>"

        elif output_format == OutputFormat.XML:
            return self._to_xml(content)

        else:  # TEXT
            if isinstance(content, str):
                return content
            return str(content)

    def _to_xml(self, content: Any) -> str:
        """Convert content to XML format."""
        if isinstance(content, str):
            return f"<content>{content}</content>"
        elif isinstance(content, dict):
            xml_parts = ["<data>"]
            for key, value in content.items():
                xml_parts.append(f"  <{key}>{value}</{key}>")
            xml_parts.append("</data>")
            return "\n".join(xml_parts)
        return f"<content>{str(content)}</content>"

    def _generate_metadata(self, user_metadata: Optional[Dict]) -> Dict:
        """
        Generate metadata for formatted output.

        Args:
            user_metadata: User-provided metadata

        Returns:
            Complete metadata dictionary
        """
        metadata = {
            "sdk_version": "1.0.0",
            "formatter": "AshborneSDK",
            "content_policy": self.content_policy.value,
            "timestamp": datetime.now().isoformat()
        }

        if user_metadata:
            metadata.update(user_metadata)

        return metadata

    def _generate_signature(self, data: Dict) -> str:
        """
        Generate cryptographic signature for watermark.

        Args:
            data: Data to sign

        Returns:
            Signature string
        """
        data_str = json.dumps(data, sort_keys=True)
        signature = hashlib.sha256(data_str.encode()).hexdigest()
        return signature

    def verify_watermark(self, content: str, expected_signature: str) -> bool:
        """
        Verify if content has a valid watermark.

        Args:
            content: Content to verify
            expected_signature: Expected watermark signature

        Returns:
            True if watermark is valid, False otherwise
        """
        # Extract watermark from content
        # This is a placeholder - actual implementation would extract and verify
        logger.info("Verifying watermark...")
        return True

    def sanitize_output(self, content: str) -> str:
        """
        Sanitize output for safe display/storage.

        Args:
            content: Content to sanitize

        Returns:
            Sanitized content
        """
        # Remove potentially harmful content
        sanitized = content.replace("<script>", "").replace("</script>", "")
        sanitized = sanitized.replace("javascript:", "")

        return sanitized
